name: Paid2Mine
version: 0.1.2
description: Allows players to get paid for mining.
main: me.pwnage.bukkit.paid2mine.Paid2Mine
commands:
  minepay:
    description: General command for Paid2Mine
    usage: /<command> -version|-reload